import { useCallback, useEffect, useState } from 'react';
import PageHeader from '../components/PageHeader';
import Notice from '../components/Notice';
import EmptyState from '../components/EmptyState';
import api from '../services/api';
import { ENDPOINTS } from '../services/endpoints';
import { formatDate, getErrorMessage, humanize, listFromResponse } from '../lib/apiHelpers';
import type { NotificationItem } from '../types';

export default function NotificationsPage() {
  const [notifications, setNotifications] = useState<NotificationItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const load = useCallback(async () => {
    setLoading(true);
    try { const response = await api.get(ENDPOINTS.notifications); setNotifications(listFromResponse<NotificationItem>(response.data)); setError(''); }
    catch (caught) { setError(getErrorMessage(caught, 'Could not load notifications. Check the URL in services/endpoints.ts.')); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);

  async function markRead(item: NotificationItem) {
    setError(''); setSuccess('');
    try { await api.post(ENDPOINTS.notificationRead(item.id)); setNotifications((current) => current.map((n) => n.id === item.id ? { ...n, read_at: new Date().toISOString() } : n)); }
    catch (caught) { setError(getErrorMessage(caught, 'Could not mark notification as read. Check the notification URL.')); }
  }

  async function markAllRead() {
    setError(''); setSuccess('');
    try { await api.post(ENDPOINTS.notificationReadAll); setNotifications((current) => current.map((n) => ({ ...n, read_at: n.read_at || new Date().toISOString() }))); setSuccess('All notifications marked as read.'); }
    catch (caught) { setError(getErrorMessage(caught, 'Could not mark all notifications as read. Check the URL in services/endpoints.ts.')); }
  }

  const unreadCount = notifications.filter((item) => !item.read_at).length;
  return <>
    <PageHeader title="Notifications" description="Stay on top of team changes, project updates, and task activity." action={<button disabled={!unreadCount || loading} onClick={() => void markAllRead()} className="rounded-xl border border-slate-700 px-4 py-2.5 text-sm font-semibold text-slate-200 transition hover:border-cyan-300/40 hover:text-cyan-200 disabled:opacity-40">Mark all read</button>} />
    {(error || success) && <div className="mb-5"><Notice message={error || success} kind={error ? 'error' : 'success'} /></div>}
    <div className="mb-4 flex items-center justify-between"><p className="text-sm text-slate-400">{unreadCount} unread</p><span className="text-xs text-slate-500">{notifications.length} total</span></div>
    {loading ? <div className="rounded-2xl border border-slate-800 p-8 text-sm text-slate-500">Loading notifications…</div> : notifications.length === 0 ? <EmptyState title="You're all caught up" description="Notifications generated by TeamFlow will appear here." /> : <div className="space-y-3">{notifications.map((item) => <article key={item.id} className={`rounded-2xl border p-5 transition ${item.read_at ? 'border-slate-800 bg-slate-900/40' : 'border-cyan-300/20 bg-slate-900/80'}`}><div className="flex gap-4"><div className={`mt-0.5 grid size-10 shrink-0 place-items-center rounded-xl ${item.read_at ? 'bg-slate-800 text-slate-400' : 'bg-cyan-300/10 text-cyan-300'}`}>♧</div><div className="min-w-0 flex-1"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-semibold text-white">{humanize(item.notification_type || 'Notification')}</h3><p className="mt-1 text-sm leading-6 text-slate-400">{item.message || item.detail || (item.metadata ? Object.entries(item.metadata).map(([key, value]) => `${humanize(key)}: ${String(value)}`).join(' · ') : 'You have a new notification.')}</p><p className="mt-2 text-xs text-slate-500">{formatDate(item.created_at)}{item.actor_username ? ` · From ${item.actor_username}` : ''}</p></div>{!item.read_at && <button onClick={() => void markRead(item)} className="shrink-0 rounded-lg border border-slate-700 px-3 py-2 text-xs font-semibold text-slate-300 hover:border-cyan-300/40 hover:text-cyan-200">Mark read</button>}</div></div></div></article>)}</div>}
  </>;
}
