# Generated by Django 6.1.1 on 2026-10-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MEMBER_ADDED', 'Member added'), ('ROLE_CHANGED', 'Role changed'), ('JOIN_REQUEST_APPROVED', 'Join request approved'), ('TASK_ASSIGNED', 'Task assigned'), ('TASK_COMPLETED', 'Task completed'), ('MEMBER_REMOVED', 'Member removed')], max_length=30),
        ),
    ]
